<?php

namespace Modules\Annotation;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-21 at 13:03:21.
 */
class AnnotationTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Annotation
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new Annotation;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Modules\Annotation\Annotation::readClass
     * @todo   Implement testReadClass().
     */
    public function testReadClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Modules\Annotation\Annotation::readFunction
     * @todo   Implement testReadFunction().
     */
    public function testReadFunction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Modules\Annotation\Annotation::readMethod
     * @todo   Implement testReadMethod().
     */
    public function testReadMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
